[package]
name = "memory-test-runner"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.10", features = ["derive"] }
num_cpus ={ version = "1.13.0" }
tokio = { version = "1.13.0", features = ["full"] }
